
export const currencies = [
  { name: 'United States Dollar', code: 'USD', symbol: '$' },
  { name: 'Euro', code: 'EUR', symbol: '€' },
  { name: 'British Pound', code: 'GBP', symbol: '£' },
  { name: 'Japanese Yen', code: 'JPY', symbol: '¥' },
  { name: 'Canadian Dollar', code: 'CAD', symbol: '$' },
  { name: 'Australian Dollar', code: 'AUD', symbol: '$' },
  { name: 'Swiss Franc', code: 'CHF', symbol: 'Fr' },
  { name: 'Chinese Yuan', code: 'CNY', symbol: '¥' },
  { name: 'Indian Rupee', code: 'INR', symbol: '₹' },
  { name: 'Brazilian Real', code: 'BRL', symbol: 'R$' },
  { name: 'Russian Ruble', code: 'RUB', symbol: '₽' },
  { name: 'South Korean Won', code: 'KRW', symbol: '₩' },
  { name: 'Mexican Peso', code: 'MXN', symbol: '$' },
  { name: 'Singapore Dollar', code: 'SGD', symbol: '$' },
  { name: 'Hong Kong Dollar', code: 'HKD', symbol: '$' },
  { name: 'Norwegian Krone', code: 'NOK', symbol: 'kr' },
  { name: 'New Zealand Dollar', code: 'NZD', symbol: '$' },
  { name: 'Swedish Krona', code: 'SEK', symbol: 'kr' },
  { name: 'South African Rand', code: 'ZAR', symbol: 'R' },
  { name: 'Turkish Lira', code: 'TRY', symbol: '₺' },
  { name: 'Saudi Riyal', code: 'SAR', symbol: '﷼' },
  { name: 'United Arab Emirates Dirham', code: 'AED', symbol: 'د.إ' },
  { name: 'Danish Krone', code: 'DKK', symbol: 'kr' },
  { name: 'Polish Złoty', code: 'PLN', symbol: 'zł' },
  { name: 'Thai Baht', code: 'THB', symbol: '฿' },
  { name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp' },
  { name: 'Czech Koruna', code: 'CZK', symbol: 'Kč' },
  { name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM' },
  { name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft' },
  { name: 'Philippine Peso', code: 'PHP', symbol: '₱' },
  { name: 'Israeli New Shekel', code: 'ILS', symbol: '₪' },
  { name: 'Pakistani Rupee', code: 'PKR', symbol: '₨' },
  { name: 'Egyptian Pound', code: 'EGP', symbol: 'E£' },
  { name: 'Nigerian Naira', code: 'NGN', symbol: '₦' },
  { name: 'Vietnamese Đồng', code: 'VND', symbol: '₫' },
  { name: 'Bangladeshi Taka', code: 'BDT', symbol: '৳' },
  { name: 'Argentine Peso', code: 'ARS', symbol: '$' },
  { name: 'Romanian Leu', code: 'RON', symbol: 'lei' },
  { name: 'Colombian Peso', code: 'COP', symbol: '$' },
  { name: 'Chilean Peso', code: 'CLP', symbol: '$' }
];
