
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpgtwgfsgitgkmudigha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZ3R3Z2ZzZ2l0Z2ttdWRpZ2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzk1MTksImV4cCI6MjA1OTg1NTUxOX0.heKuH7ajFsTiGzJXXdNVodGfIzawBPMuMh3S9aoqdNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to set custom auth for business users
export const setSupabaseBusinessAuth = (businessUserId: string) => {
  // For business users, we'll use custom headers via fetch interceptor
  // This approach avoids accessing protected properties
  const previousFetch = globalThis.fetch;
  
  globalThis.fetch = async (input, init) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    
    // Only intercept Supabase API requests
    if (url.includes(SUPABASE_URL)) {
      init = init || {};
      init.headers = init.headers || {};
      
      // Add our custom business user header
      Object.assign(init.headers, {
        'business-user-id': businessUserId
      });
    }
    
    return previousFetch(input, init);
  };
};

// Function to clear custom auth
export const clearSupabaseBusinessAuth = () => {
  // Reset fetch to its original implementation
  delete (globalThis as any).__supabaseFetchInterceptor;
  
  // If we stored the previous fetch implementation, restore it
  if ((globalThis as any).__originalFetch) {
    globalThis.fetch = (globalThis as any).__originalFetch;
    delete (globalThis as any).__originalFetch;
  }
};
